cliente/urls.py
from django.urls import path
from .views import ClienteList, ClienteNew, ClienteEdit, AbonoList, AbonoNew


urlpatterns = [
    path('abono/',AbonoList.as_view(), name='abono'),
    path('abono/nuevo',AbonoNew.as_view(), name='abono_nuevo'),

    path('cliente/',ClienteList.as_view(), name='cliente'),
    path('cliente/nuevo',ClienteNew.as_view(), name='cliente_nuevo'),
    path('cliente/edit/<int:pk>', ClienteEdit.as_view(), name="cliente_edit"),


]

inv/urls.py
from django.urls import path
from .views import CategoriaList, CategoriaNew,  ProductoList, ProductoEdit
from django.conf.urls.static import static
from inv import views as vistas
from pos import settings

MEDIA_URL = '/media'
MEDIA_ROOT = '/media/'

urlpatterns = [
    path('categoria',CategoriaList.as_view(), name='categoria'),
    path('categoria/nueva',CategoriaNew.as_view(), name='categoria_nueva'),
    path('producto',ProductoList.as_view(), name='producto'),
    path('producto/nuevo',vistas.subir_imagen, name='producto_nuevo'),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name="producto_edit"),
    path('producto/codigoBarras/<str:pk>', vistas.generar_barras, name='generar_barras'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('cliente.urls','cliente'), namespace='cliente')),
    path('',include(('contabilidad.urls','contabilidad'), namespace='contabilidad')),
    path('',include(('inv.urls','inv'), namespace='inv')),
    path('',include(('pedido.urls','pedido'), namespace='pedido')),
    path('',include(('venta.urls','venta'), namespace='venta')),
]
admin.site.site_header = 'BOTANAS GUADALUPE'

cliente/models.py
from django.db import models

from venta.models import VentaGeneral


from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from decimal import Decimal
from django.db.models import Sum


class Cliente(models.Model):
    nombre = models.CharField(max_length=500)
    telefono = models.CharField(max_length=500)
    direccion = models.CharField(max_length=500)
    deuda = models.DecimalField(max_digits=50, decimal_places=2,default=0)

    def __str__(self):
        return '{}'.format(self.nombre)


class Abono(models.Model):
    nombre = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    num_venta = models.ForeignKey(VentaGeneral, on_delete=models.CASCADE)
    abono = models.DecimalField(max_digits=50, decimal_places=2,default=0)
    fa = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.nombre)
    




@receiver(post_save, sender=Abono)
def update_resto(sender, instance, **kwargs):
    instance.num_venta.resto += instance.abono
    instance.num_venta.resto_total =  instance.num_venta.total - instance.num_venta.resto
    instance.num_venta.save()


@receiver(post_save, sender=Abono)
def update_stock(sender, instance, **kwargs):
    instance.nombre.deuda = instance.nombre.deuda - instance.abono
    instance.nombre.save()

cliente/forms.py
from django import forms

from .models import Cliente, Abono

class AbonoForm(forms.ModelForm):
    class Meta:
        model = Abono
        fields = ['nombre', 'num_venta', 'abono']
        labels = {'nombre':"Nombre", 'num_venta':"Número de Venta", 'abono':"Abono"}
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'telefono', 'direccion']
        labels = {'nombre':"Nombre", 'telefono':"Telefono", 'direccion':"Direccion"}
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

cliente/views.py
from django.shortcuts import HttpResponseRedirect, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin,\
     PermissionRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from .models import Cliente, Abono
from .forms import ClienteForm, AbonoForm

class AbonoList(LoginRequiredMixin, generic.ListView):
    login_url = "contabilidad:login"
    model = Abono
    permission_required='cliente.view_abono'
    template_name = 'cliente/abono_list.html'
    context_object_name = 'obj'

class AbonoNew(SuccessMessageMixin,\
    generic.CreateView):
    login_url = "contabilidad:login"
    permission_required="cliente.add_abono"
    model=Abono
    template_name="cliente/abono_form.html"
    context_object_name = "obj"
    form_class=AbonoForm
    success_url=reverse_lazy("cliente:abono")

class ClienteList(LoginRequiredMixin, generic.ListView):
    login_url = "contabilidad:login"
    model = Cliente
    permission_required='cliente.view_cliente'
    template_name = 'cliente/cliente_list.html'
    context_object_name = 'obj'

class ClienteNew(SuccessMessageMixin,\
    generic.CreateView):
    login_url = "contabilidad:login"
    permission_required="cliente.add_cliente"
    model=Cliente
    template_name="cliente/cliente_form.html"
    context_object_name = "obj"
    form_class=ClienteForm
    success_url=reverse_lazy("cliente:cliente")

class ClienteEdit(LoginRequiredMixin, generic.UpdateView):
    model = Cliente
    template_name = "cliente/cliente_form.html"
    context_object_name = 'obj'
    form_class = ClienteForm
    success_url = reverse_lazy("cliente:cliente")
    permission_required = "cliente.change_cliente"

cliente/templates/cliente/abono_form.html
{% extends 'base/home.html' %}
{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Agregar Cliente</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Agregar Cliente <small>Botanas Guadalupe</small></h3>
                </div>
                <form method="POST" id="quickForm">
                    {% csrf_token %}
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <div class="col-sm-6">
                      <ol class="breadcrumb float-sm-right">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                      </ol>
                    </div>
                </form>
              </div>
            </div>
        </div>
</section>
</div>
{%endblock body%}

cliente/templates/cliente/abono_list.html
{% extends 'base/home.html' %}
{% load humanize %}
{% block body %}
<br>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Abonos</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <a href="{% url 'cliente:abono_nuevo'  %}">
                  <button type="button" class="btn btn-block bg-gradient-success">Nuevo Abono</button>
                </a>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
{% if user.is_staff %}  
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>NOMBRE</th>
                  <th>NÚMERO DE VENTA</th>
                  <th>ABONO</th>
                  <th>FECHA DE ABONO</th>
                </tr>
                </thead>
                <tbody>
                    {% for co in obj %}
                    <tr>
                      <td>{{ co.nombre }}</td>
                      <td>{{ co.num_venta }}</td>
                      <td>${{ co.abono | intcomma }}</td>
                      <td>{{ co.fa }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
{% endif %}
</div>
{% endblock body %}

cliente/templates/cliente/cliente_form.html
{% extends 'base/home.html' %}
{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Agregar Cliente</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Agregar Cliente <small>Botanas Guadalupe</small></h3>
                </div>
                <form method="POST" id="quickForm">
                    {% csrf_token %}
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <div class="col-sm-6">
                      <ol class="breadcrumb float-sm-right">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                      </ol>
                    </div>
                </form>
              </div>
            </div>
        </div>
</section>
</div>
{%endblock body%}

cliente/templates/cliente/cliente_list.html
{% extends 'base/home.html' %}
{% load humanize %}
{% block body %}
<br>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Clientes</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <a href="{% url 'cliente:cliente_nuevo'  %}">
                  <button type="button" class="btn btn-block bg-gradient-success">Nuevo Cliente</button>
                </a>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
{% if user.is_staff %}  
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>NOMBRE</th>
                  <th>TELEFONO</th>
                  <th>DIRECCIÓN</th>
                  <th>DEUDA</th>
                  <th>EDITAR</th>
                </tr>
                </thead>
                <tbody>
                    {% for co in obj %}
                    <tr>
                      <td>{{ co.nombre }}</td>
                      <td>{{ co.telefono }}</td>
                      <td>{{ co.direccion }}</td>
                      <td>${{ co.deuda | intcomma }}</td>
                      <td><a href="{% url 'cliente:cliente_edit'  co.id %}" class="href btn btn-warning btn-circle">
                          <i class="fa fa-edit"></i>
                      </a></td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
{% endif %}
</div>
{% endblock body %}