inv/urls.py
from django.urls import path
from .views import CategoriaList, CategoriaNew,  ProductoList, ProductoEdit
from django.conf.urls.static import static
from inv import views as vistas
from pos import settings

MEDIA_URL = '/media'
MEDIA_ROOT = '/media/'

urlpatterns = [
    path('categoria',CategoriaList.as_view(), name='categoria'),
    path('categoria/nueva',CategoriaNew.as_view(), name='categoria_nueva'),
    path('producto',ProductoList.as_view(), name='producto'),
    path('producto/nuevo',vistas.subir_imagen, name='producto_nuevo'),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name="producto_edit"),
    path('producto/codigoBarras/<str:pk>', vistas.generar_barras, name='generar_barras'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('cliente.urls','cliente'), namespace='cliente')),
    path('',include(('contabilidad.urls','contabilidad'), namespace='contabilidad')),
    path('',include(('inv.urls','inv'), namespace='inv')),
    path('',include(('pedido.urls','pedido'), namespace='pedido')),
    path('',include(('venta.urls','venta'), namespace='venta')),
]
admin.site.site_header = 'BOTANAS GUADALUPE'

inv/models.py
from django.db import models
#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from barcode import EAN13
from barcode.writer import ImageWriter
from barcode import get_barcode

def generaCodigoBarra(idProducto):
    codigo = str(idProducto).zfill(12)  
    cod = get_barcode('EAN13', codigo, writer=ImageWriter())
    return cod



class Categoria(models.Model):
    nombre = models.CharField(
        max_length=100,
        help_text='Descripción de la Categoría',
        unique=True
    )
    def __str__(self):
        return '{}'.format(self.nombre)
    
    def save(self):
        self.nombre = self.nombre.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural= "Categorias"



class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='inv/fotos', blank=True)
    caducidad = models.DateField(blank=True)
    lote = models.CharField(max_length=200, blank=True)
    codigo_barra = models.CharField(max_length=200, blank=True)
    descuento = models.FloatField(default=0)
    precio_descuento = models.FloatField(default=0, editable=False)
    precio_compra = models.FloatField(default=0)
    precio_venta = models.FloatField(default=0)
    stock_inicial = models.IntegerField(default=0)
    stock_final = models.IntegerField(default=0)
    ganancia = models.FloatField(default=0, editable=False, blank = True)

    def __str__(self):
        return '{}:{}'.format(self.nombre,self.codigo_barra)
    
    def save(self):
        self.precio_descuento = ((100 - self.descuento)*self.precio_venta)/100
        #self.descripcion = self.descripcion.upper()
        self.ganancia = (self.precio_descuento - self.precio_compra)
        super(Producto,self).save()
        self.codigo_barra = generaCodigoBarra(self.id) 
        super(Producto,self).save()
    
    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('nombre', 'codigo_barra')


 

inv/forms.py
from django import forms

from .models import Categoria, Producto

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']
        labels = {'nombre':"Nombre"}
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre','categoria','img', 'lote', 'caducidad', 'descuento',
                    'precio_compra', 'precio_venta', 'stock_inicial', 'stock_final','codigo_barra']
        labels = {'nombre':"Nombre", 'categoria':"Categoría",
                    'img':"Imagen", 'lote':"Lote", 'caducidad':"Caducidad",
                    'descuento':"Descuento",
                    'precio_compra':"Precio de Compra", 'precio_venta':"Precio de Venta", 'stock_inicial':"Stock Inicial",
                    'stock_final':"Stock Final", 'codigo_barra':"Código de Barra"}
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

inv/views.py
from django.http.response import HttpResponseBadRequest
from django.shortcuts import HttpResponseRedirect, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin,\
     PermissionRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from .models import Categoria, Producto
from .forms import CategoriaForm, ProductoForm
from inv import models as modelsInv

from django.http import FileResponse
from barcode import EAN13
from barcode.writer import ImageWriter
from io import BytesIO
import io
from barcode import generate
from PIL import Image

class CategoriaList(LoginRequiredMixin, generic.ListView):
    login_url = "contabilidad:login"
    model = Categoria
    permission_required='inv.view_categoria'
    template_name = 'inv/categoria_list.html'
    context_object_name = 'obj'

class CategoriaNew(SuccessMessageMixin,\
    generic.CreateView):
    login_url = "contabilidad:login"
    permission_required="inv.add_categoria"
    model=Categoria
    template_name="inv/categoria_form.html"
    context_object_name = "obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:categoria")
    success_message="Categoria Creada Satisfactoriamente"


class ProductoList(LoginRequiredMixin, generic.ListView):
    login_url = "contabilidad:login"
    model = Producto
    permission_required='inv.view_producto'
    template_name = 'inv/producto_list.html'
    context_object_name = 'obj'


@login_required(login_url='bases:login')
def subir_imagen(request):
    form = ProductoForm()
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            producto = form.save(commit=False)
            producto.img = request.FILES['img']
            producto.save()
            return redirect("inv:producto")

    context = {"form": form,}
    return render(request, 'inv/producto_form.html', context)

class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy("inv:producto")
    success_message = "Producto Editado Correctamente"
    permission_required = "inv.change_producto"

@login_required(login_url='admin:login')
def generar_barras(request,pk):
    producto = modelsInv.Producto.objects.filter(id=pk).exists()
    attachment = False #False si solo se quiere visualizar
    ancho = 500
    alto =  250
    if producto:
        try:
            producto = modelsInv.Producto.objects.get(id=pk)
            codigo = producto.codigo_barra
            fp = BytesIO()
            generate('EAN13', codigo, writer=ImageWriter(), output=fp)
            fp.seek(io.SEEK_SET)
            img = Image.open(io.BytesIO(fp.read()))
            image = img.resize((ancho, alto), Image.ANTIALIAS)
            output = BytesIO()
            image.save(output, format="png", optimize=True)
            name = str(producto.id) + ".png"
            output.seek(io.SEEK_SET)
            response = FileResponse(output, as_attachment=attachment, filename=name)
            return response 
        except:
            return HttpResponseBadRequest("Error al generar el código de barras")
    else:
        return HttpResponseBadRequest("El producto buscado no existe")

inv/templates/inv/categoria_form.html
{% extends 'base/home.html' %}
{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Agregar Categoría</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Agregar Categoría <small>Botanas Guadalupe</small></h3>
                </div>
                <form method="POST" id="quickForm">
                    {% csrf_token %}
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <div class="col-sm-6">
                      <ol class="breadcrumb float-sm-right">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                      </ol>
                    </div>
                </form>
              </div>
            </div>
        </div>
</section>
</div>
{%endblock body%}

inv/templates/inv/categoria_list.html
{% extends 'base/home.html' %}
{% load humanize %}
{% block body %}
<br>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Categoría</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <a href="{% url 'inv:categoria_nueva'  %}">
                  <button type="button" class="btn btn-block bg-gradient-success">Nueva Categoría</button>
                </a>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>NOMBRE</th>
                </tr>
                </thead>
                <tbody>
                    {% for ca in obj %}
                    <tr>
                      <td>{{ ca.nombre }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
</div>
{% endblock body %}

inv/templates/inv/producto_form.html
{% extends 'base/home.html' %}
{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Agregar Producto</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Agregar Producto <small>Botanas Guadalupe</small></h3>
                </div>
                <form method="POST" enctype=multipart/form-data id="quickForm">
                    {% csrf_token %}
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <div class="col-sm-6">
                      <ol class="breadcrumb float-sm-right">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                      </ol>
                    </div>
                </form>
              </div>
            </div>
        </div>
</section>
</div>
{%endblock body%}

inv/templates/inv/producto_list.html
{% extends 'base/home.html' %}
{% load humanize %}
{% block body %}
<br>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Producto</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <a href="{% url 'inv:producto_nuevo'  %}">
                  <button type="button" class="btn btn-block bg-gradient-success">Nuevo Producto</button>
                </a>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>IMPRIMIR CÓDIGO BARRAS</th>
                  <th>NOMBRE</th>
                  <th>CATEGORIA</th>
                  <th>IMAGEN</th>
                  <th>CADUCIDAD</th>
                  <th>CODIGO DE BARRA</th>
                  <th>DESCUENTO</th>
                  <th>PRECIO CON DESCUENTO</th>
                  <th>PRECIO DE COMPRA</th>
                  <th>PRECIO DE VENTA</th>
                  <th>GANANCIA</th>
                  <th>STOCK INICIAL</th>
                  <th>STOCK FINAL</th>
                  <th>EDITAR</th>
                </tr>
                </thead>
                <tbody>
                    {% for pro in obj %}
                    <tr>
                      <td><a href="{% url 'inv:generar_barras'  pro.id %}" target="_blank" class="href btn btn-primary btn-circle">
                          <i class="fa fa-print"></i>
                      </a></td>
                      <td>{{ pro.nombre }}</td>
                      <td>{{ pro.categoria }}</td>
                      <td><img style="width: 100%;" src="{{ pro.img.url }}"></td>
                      <td>{{ pro.caducidad }}</td>
                      <td>{{ pro.codigo_barra }}</td>
                      <td>{{ pro.descuento }}</td>
                      <td>{{ pro.precio_descuento }}</td>
                      <td>{{ pro.precio_compra }}</td>
                      <td>{{ pro.precio_venta }}</td>
                      <td>{{ pro.ganancia }}</td>
                      <td>{{ pro.stock_inicial }}</td>
                      <td>{{ pro.stock_final }}</td>
                      <td><a href="{% url 'inv:producto_edit'  pro.id %}" class="href btn btn-warning btn-circle">
                          <i class="fa fa-edit"></i>
                      </a></td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
</div>
{% endblock body %}