inv/urls.py
from django.urls import path
from .views import CategoriaList, CategoriaNew,  ProductoList, ProductoEdit
from django.conf.urls.static import static
from inv import views as vistas
from pos import settings

MEDIA_URL = '/media'
MEDIA_ROOT = '/media/'

urlpatterns = [
    path('categoria',CategoriaList.as_view(), name='categoria'),
    path('categoria/nueva',CategoriaNew.as_view(), name='categoria_nueva'),
    path('producto',ProductoList.as_view(), name='producto'),
    path('producto/nuevo',vistas.subir_imagen, name='producto_nuevo'),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name="producto_edit"),
    path('producto/codigoBarras/<str:pk>', vistas.generar_barras, name='generar_barras'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views
from .views import CompraList

urlpatterns = [
    path('compra',CompraList.as_view(), name='compra'),
    path('compra/nueva', views.compraNew, name='compra_nueva'),

]

pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('cliente.urls','cliente'), namespace='cliente')),
    path('',include(('contabilidad.urls','contabilidad'), namespace='contabilidad')),
    path('',include(('inv.urls','inv'), namespace='inv')),
    path('',include(('pedido.urls','pedido'), namespace='pedido')),
    path('',include(('venta.urls','venta'), namespace='venta')),
]
admin.site.site_header = 'BOTANAS GUADALUPE'

pedido/models.py
from django.db import models
#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from django.contrib.auth.models import User

class Compra(models.Model):
    fc = models.DateTimeField(auto_now_add=True)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    importe = models.FloatField(default=0, editable=False)
    image_producto = models.ImageField(null=True, blank=True,  upload_to='pedido/compras')

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.importe = self.cantidad * self.precio
        super(Compra, self).save()

pedido/forms.py
from django import forms

from .models import Compra

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['vendedor', 'cantidad', 'descripcion', 'precio', 'image_producto']
        labels = {'vendedor':"Vendedor", 'cantidad':"Cantidad", 'descripcion':"Descripción",
                    'precio':"Precio", 'image_producto':"Imagen del Producto"}
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

pedido/views.py
from django.shortcuts import HttpResponseRedirect, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin,\
     PermissionRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from .models import Compra
from .forms import CompraForm

class CompraList(LoginRequiredMixin, generic.ListView):
    login_url = "contabilidad:login"
    model = Compra
    permission_required='pedido.view_compra'
    template_name = 'pedido/compra_list.html'
    context_object_name = 'obj'

@login_required(login_url="bases:login")
def compraNew(request):
    form = CompraForm()
    if request.method == 'POST':
        form = CompraForm(request.POST, request.FILES)
        if form.is_valid():
            img = form.save(commit=False)
            img.image_producto = request.FILES['image_producto']
            img.save()
            return redirect("pedido:compra")

    context = {'form': form}
    return render(request, "pedido/compra_form.html", context)

pedido/templates/pedido/compra_form.html
{% extends 'base/home.html' %}
{% block body %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Agregar Compra</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Agregar Compra <small>Botanas Guadalupe</small></h3>
                </div>
                <form method="POST" enctype=multipart/form-data id="quickForm" >
                    {% csrf_token %}
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <div class="col-sm-6">
                      <ol class="breadcrumb float-sm-right">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                      </ol>
                    </div>
                </form>
              </div>
            </div>
        </div>
</section>
</div>
{%endblock body%}

pedido/templates/pedido/compra_list.html
{% extends 'base/home.html' %}
{% load humanize %}
{% block body %}
<br>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Compras</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <a href="{% url 'pedido:compra_nueva'  %}">
                  <button type="button" class="btn btn-block bg-gradient-success">Nueva Compra</button>
                </a>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>FECHA DE CREACIÓN</th>
                  <th>VENDEDOR</th>
                  <th>CANTIDAD</th>
                  <th>DESCRIPCIÓN</th>
                  <th>PRECIO</th>
                  <th>IMPORTE</th>
                  <th>IMAGEN</th>
                </tr>
                </thead>
                <tbody>
                    {% for com in obj %}
                    <tr>
                      <td>{{ com.fc }}</td>
                      <td>{{ com.vendedor }}</td>
                      <td>{{ com.cantidad }}</td>
                      <td>{{ com.descripcion }}</td>
                      <td>${{ com.precio | intcomma}}</td>
                      <td>${{ com.importe | intcomma}}</td>
                      <td><img style="width: 100%;" src="{{ com.image_producto.url }}"></td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
</div>
{% endblock body %}